name: PowerShell script
author: Pooya Kharamesh
inputs:
  eventId:
      description: The event Id of the workflow
      required: true

runs:
  using: composite
  steps:
    - id : WorkflowInitialize
      run: ${{ github.action_path }}/WorkflowInitialize.ps1 -eventId '${{ inputs.eventId }}'
      shell: PowerShell

outputs:
  correlationId:
    description: A correlation Id for the workflow
    value: ${{ steps.WorkflowInitialize.outputs.correlationId }}
  telemetryScope:
    description: A telemetryScope that covers the workflow
    value: ${{ steps.WorkflowInitialize.outputs.telemetryScope }}
branding:
  icon: terminal
  color: blue
