lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
markdown: kramdown
remote-theme: pages-themes/midnight@v0.2.0
baseurl: AL-Go/
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ""
    values:
      title: "AL-Go for GitHub"
      description: "The plug-and-play DevOps solution for Business Central app development on GitHub"