name: PowerShell script
author: Freddy Kristiansen
inputs:
  settings:
    description: Settings from template repository in compressed Json format
    required: false
    default: '{"keyVaultName": ""}'
  secrets:
    description: Comma separated list of Secrets to get
    required: true
  updateSettingsWithValues:
    description: Specifies if the values of secrets should be updated
    required: false
    default: 'N'
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/ReadSecrets.ps1 -settings '${{ inputs.settings }}' -secrets '${{ inputs.secrets }}' -updateSettingsWithValues ('${{ inputs.updateSettingsWithValues }}' -eq 'Y')
      shell: PowerShell
branding:
  icon: terminal
  color: blue