name: Increment Version Number

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: New Version Number (Major.Minor)
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  initialization :
    runs-on: windows-latest
    outputs:
      telemetryScope: ${{ steps.init.outputs.telemetryScope }}
    steps:
      - id: init
        uses: microsoft/AL-Go/InitWorkflow@main
        with: 
          eventId : "DO0096"

  update:
    runs-on: windows-latest
    needs : [ initialization ]

    steps:
      - name: Increment Version Number
        uses: microsoft/AL-Go/IncrementVersionNumber@main
        with:
          parentTelemetryScope: ${{ needs.initialization.outputs.telemetryScope }}
          versionNumber: ${{ github.event.inputs.versionNumber }}
          directCommit: ${{ github.event.inputs.directCommit }}
  
  postProcess :
    runs-on: windows-latest
    needs : [ initialization , update ]
    steps:
      - name: Finalizing the workflow
        id : postProcess
        uses: microsoft/AL-Go/workflowpostprocess@main
        with: 
          eventId : "DO0096"
          telemetryScope : ${{ needs.initialization.outputs.telemetryScope }}                   
