name: Update AL-Go System Files

on:
  workflow_dispatch:
    inputs:
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  initialization :
    runs-on: windows-latest
    outputs:
      telemetryScope: ${{ steps.init.outputs.telemetryScope }}
      correlationId: ${{ steps.init.outputs.correlationId }}  
    steps:
      - id: init
        uses: microsoft/AL-Go/InitWorkflow@main
        with: 
          workflowName : "DO0098"

  update:
    runs-on: windows-latest
    needs : [ initialization ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go/ReadSettings@main
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          get: KeyVaultName,GhTokenWorkflowSecretName,TemplateUrl,TemplateBranch

      - name: Read secrets
        uses: microsoft/AL-Go/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          settingsJson: ${{ env.Settings }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: Update AL-Go system files
        uses: microsoft/AL-Go/CheckForUpdates@main
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          token: ${{ env.ghTokenWorkflow }}
          update: Y
          templateUrl: ${{ env.TemplateUrl }}
          templateBranch: ${{ env.TemplateBranch }}
          directCommit: ${{ github.event.inputs.directCommit }}
