name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  Test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          try {
            $failedTests = Invoke-Pester @(Get-ChildItem -Path "Tests\*.Test.ps1") -OutputFile "TestResults.xml" -OutputFormat JUnitXml -PassThru
            if ($TestResults.FailedCount -gt 0) {
              Write-Host "::Error::$($TestResults.FailedCount) tests are failing"
              exit 1
            }
          }
          catch {
            Write-Host "::Error::Error when running tests. The Error was $($_.Exception.Message)"
            exit 1
          }
