name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  SetupRepositories:
    runs-on: [ windows-latest ]
    outputs:
      actionsRepo: ${{ steps.SetupRepositories.outputs.actionsRepo }}
      perTenantExtentionRepo: ${{ steps.SetupRepositories.outputs.perTenantExtensionRepo }}
      appSourceAppRepo: ${{ steps.SetupRepositories.outputs.appSourceAppRepo }}

    steps:
      - uses: actions/checkout@v2

      - name: SetupRepositories
        id: SetupRepositories
        run: e2eTests\SetupRepositories.ps1 -actor '${{ github.actor }}' -token '${{ Secrets.OrgPAT }}'

  Test:
    runs-on: [ windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: Tests\RunTests.ps1

  TestAlGoPte:
    runs-on: [ windows-latest ]
    needs: [ SetupRepositories ]

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: e2eTests\Test-AL-Go-pte.ps1 -actor '${{ github.actor }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -adminCenterApiCredentials '${{ Secrets.AdminCenterApiCredentials }}'

  RemoveRepositories:
    runs-on: [ windows-latest ]
    needs: [ SetupRepositories, TestAlGoPte ]
    if: (needs.SetupRepositories.result == 'Success')

    steps:
      - uses: actions/checkout@v2

      - name: Remove Repositories
        run: e2eTests\RemoveRepositories.ps1 -actor '${{ github.actor }}' -token '${{ Secrets.OrgPAT }}' -actionsRepo '${{ needs.SetupRepositories.outputs.actionsRepo }}' -perTenantExtensionRepo '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -appSourceAppRepo '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}'
