name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  Test:
    runs-on: [ windows-latest ]
    outputs:
      orgpatset: ${{ steps.checksecrets.outputs.orgpatset}}
      licensefileurlset: ${{ steps.checksecrets.outputs.licensefileurlset}}
    steps:
      - uses: actions/checkout@v2

      - name: Rate Limits
        run: |
          ((Invoke-WebRequest -UseBasicParsing -Uri "https://api.github.com/rate_limit").Content | ConvertFrom-Json).rate | Out-Host

      - name: Run basic tests
        run: Tests\RunTests.ps1
      
      - name: Check secrets
        id: checksecrets
        run: |
          $orgpatset = @('Yes','No')['${{ Secrets.OrgPAT }}' -eq '']
          Write-Host "::set-output name=orgpatset::$orgpatset"
          Write-Host "set-output name=orgpatset::$orgpatset"
          $licensefileurlset = @('Yes','No')['${{ Secrets.LicenseFileUrl }}' -eq '']
          Write-Host "::set-output name=licensefileurlset::$licensefileurlset"
          Write-Host "set-output name=licensefileurlset::$licensefileurlset"

  SetupRepositories:
    runs-on: [ windows-latest ]
    needs: [ Test ]
    if: ('${{ needs.Test.outputs.orgpatset }}' == 'Yes')
    outputs:
      actionsRepo: ${{ steps.setup.outputs.actionsRepo }}
      perTenantExtensionRepo: ${{ steps.setup.outputs.perTenantExtensionRepo }}
      appSourceAppRepo: ${{ steps.setup.outputs.appSourceAppRepo }}
    steps:
      - uses: actions/checkout@v2

      - name: Rate Limits
        run: |
          ((Invoke-WebRequest -UseBasicParsing -Uri "https://api.github.com/rate_limit").Content | ConvertFrom-Json).rate | Out-Host

      - name: Setup Repositories
        id: setup
        run: e2eTests\SetupRepositories.ps1 -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}'

  TestAlGoPte:
    runs-on: [ windows-latest ]
    needs: [ Test, SetupRepositories ]
    if: ('${{ needs.Test.outputs.orgpatset }}' == 'Yes')
    steps:
      - uses: actions/checkout@v2

      - name: Rate Limits
        run: |
          ((Invoke-WebRequest -UseBasicParsing -Uri "https://api.github.com/rate_limit").Content | ConvertFrom-Json).rate | Out-Host

      - name: Run tests
        run: e2eTests\Test-AL-Go-pte.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -adminCenterApiCredentials '${{ Secrets.adminCenterApiCredentials }}'

  TestAlGoPteMultiProject:
    runs-on: [ windows-latest ]
    needs: [ Test, SetupRepositories ]
    if: ('${{ needs.Test.outputs.orgpatset }}' == 'Yes')
    steps:
      - uses: actions/checkout@v2

      - name: Rate Limits
        run: |
          ((Invoke-WebRequest -UseBasicParsing -Uri "https://api.github.com/rate_limit").Content | ConvertFrom-Json).rate | Out-Host

      - name: Run tests
        run: e2eTests\Test-AL-Go-pte.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -adminCenterApiCredentials '${{ Secrets.adminCenterApiCredentials }}' -multiProject

  TestAlGoAppSource:
    runs-on: [ windows-latest ]
    needs: [ Test, SetupRepositories ]
    if: ('${{ needs.Test.outputs.orgpatset }}' == 'Yes')
    steps:
      - uses: actions/checkout@v2

      - name: Rate Limits
        run: |
          ((Invoke-WebRequest -UseBasicParsing -Uri "https://api.github.com/rate_limit").Content | ConvertFrom-Json).rate | Out-Host

      - name: Run tests
        run: e2eTests\Test-AL-Go-appSource.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}' -adminCenterApiCredentials '' -licenseFileUrl '${{ Secrets.LicenseFileUrl }}'

  TestAlGoAppSourceMultiProject:
    runs-on: [ windows-latest ]
    needs: [ Test, SetupRepositories ]
    if: ('${{ needs.Test.outputs.orgpatset }}' == 'Yes')
    steps:
      - uses: actions/checkout@v2

      - name: Rate Limits
        run: |
          ((Invoke-WebRequest -UseBasicParsing -Uri "https://api.github.com/rate_limit").Content | ConvertFrom-Json).rate | Out-Host

      - name: Run tests
        run: e2eTests\Test-AL-Go-appSource.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}' -adminCenterApiCredentials '' -licenseFileUrl '${{ Secrets.LicenseFileUrl }}' -multiProject

  RemoveRepositories:
    runs-on: [ windows-latest ]
    needs: [ Test, SetupRepositories, TestAlGoPte, TestAlGoPteMultiProject, TestAlGoAppSource, TestAlGoAppSourceMultiProject ]
    if: always() && ('${{ needs.SetupRepositories.result }}' == 'Success') && ('${{ needs.Test.outputs.orgpatset }}' == 'Yes')
    steps:
      - uses: actions/checkout@v2

      - name: Rate Limits
        run: |
          ((Invoke-WebRequest -UseBasicParsing -Uri "https://api.github.com/rate_limit").Content | ConvertFrom-Json).rate | Out-Host

      - name: Remove Repositories
        run: e2eTests\RemoveRepositories.ps1 -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -actionsRepo '${{ needs.SetupRepositories.outputs.actionsRepo }}' -perTenantExtensionRepo '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -appSourceAppRepo '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}'
