name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy to (default is main)
        required: false
        default: 'main'

defaults:
  run:
    shell: PowerShell

jobs:
  Deploy:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: |
          try {
            $githubOwner = "$ENV:GITHUB_REPOSITORY_OWNER"
            $token = ${{ Secrets.OrgPAT }}
            if (!$token) {
              throw "No OrgPAT secret found"
            }
            else {
              $settings = [ordered]@{
                  "githubOwner" = $githubOwner
                  "actionsRepo" = "AL-Go-Actions"
                  "perTenantExtensionRepo" = "AL-Go-PTE"
                  "appSourceAppRepo" = "AL-Go-AppSource"
                  "branch" = ${{ github.event.inputs.branch }}
                  "localFolder" = ""
                  "baseFolder" = [System.IO.Path]::GetTempPath()
              }
              $settingsFile = Join-Path $settings.baseFolder "deploy.json"
              $settings | ConvertTo-Json | Set-Content $settingsFile -Encoding UTF8
              . ".\Internal\Deploy.ps1" -configName $settingsFile -githubOwner $githubOwner -token $token -github
            }
          }
          catch {
            Write-Host "::Error::Error deploying repositories. The error was $($_.Exception.Message)"
          }
