name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy to (default is main)
        required: false
        default: 'main'
      copyToMain:
        description: Additionally deploy templates to main branch (No for insider and hotfix)
        required: false
        default: 'Yes'

defaults:
  run:
    shell: PowerShell

jobs:
  Check:
    runs-on: [ windows-latest ]
    steps:
      - name: Check secrets
        run: |
          if ('${{ Secrets.OrgPAT }}' -eq '') {
            Write-Host "::Error::In order to run deploy workflow, you need a Secret called OrgPAT containing a valid Personal Access Token"
            exit 1
          }

  Deploy:
    runs-on: [ windows-latest ]
    needs: [ Check ]
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: |
          try {
            $githubOwner = "$ENV:GITHUB_REPOSITORY_OWNER"
            $token = '${{ Secrets.OrgPAT }}'
            if (!$token) {
              throw "No OrgPAT secret found"
            }
            else {
              $settings = [ordered]@{
                  "githubOwner" = $githubOwner
                  "actionsRepo" = "AL-Go-Actions"
                  "perTenantExtensionRepo" = "AL-Go-PTE"
                  "appSourceAppRepo" = "AL-Go-AppSource"
                  "branch" = '${{ github.event.inputs.branch }}'
                  "copyToMain" = ('${{ github.event.inputs.branch }}' -eq 'Yes')
                  "localFolder" = ""
                  "baseFolder" = [System.IO.Path]::GetTempPath()
              }
              $settingsFile = Join-Path $settings.baseFolder "deploy.json"
              $settings | ConvertTo-Json | Set-Content $settingsFile -Encoding UTF8
              . ".\Internal\Deploy.ps1" -configName $settingsFile -githubOwner $githubOwner -token $token -github
            }
          }
          catch {
            Write-Host "::Error::Error deploying repositories. The error was $($_.Exception.Message)"
            exit 1
          }
