name: End to end tests

on:
  workflow_dispatch:
    inputs:
      ref:
        description: ref on which to run the end-2-end tests (default is head_sha on main)
        required: false
        default: ''

defaults:
  run:
    shell: PowerShell

jobs:
  Check:
    runs-on: [ windows-latest ]
    steps:
      - name: Check secrets
        run: |
          $err = $false
          if ('${{ Secrets.OrgPAT }}' -eq '') {
            Write-Host "::Error::In order to run end to end tests, you need a Secret called OrgPAT containing a valid Personal Access Token"
            $err = $true
          }
          if ('${{ Secrets.githubOwner }}' -eq '') {
            Write-Host "::Error::In order to run end to end tests, you need a Secret called githubOwner containing a the name of the owner of temp repositories"
            $err = $true
          }
          if ('${{ Secrets.adminCenterApiCredentials }}' -eq '') {
            Write-Host "::Error::In order to run end to end tests, you need a Secret called adminCenterApiCredentials containing API access credentials for BC Admin Center"
            $err = $true
          }
          if ('${{ Secrets.licenseFileUrl }}' -eq '') {
            Write-Host "::Error::In order to run end to end tests, you need a Secret called licenseFileUrl containing a secure Url to a build license file"
            $err = $true
          }
          if ($err) {
            exit 1
          }

  SetupRepositories:
    runs-on: [ windows-latest ]
    needs: [ Check ]
    outputs:
      actionsRepo: ${{ steps.setup.outputs.actionsRepo }}
      perTenantExtensionRepo: ${{ steps.setup.outputs.perTenantExtensionRepo }}
      appSourceAppRepo: ${{ steps.setup.outputs.appSourceAppRepo }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Repositories
        id: setup
        run: e2eTests\SetupRepositories.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}'
  
  CalculateReleases:
    runs-on: [ windows-latest ]
    needs: [ Check ]
    outputs:
      releases: ${{ steps.calculatereleases.outputs.releases }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: CalculateReleases
        id: calculateReleases
        run: |
          $modulePath = (Get-Item ".\e2eTests\e2eTestHelper.psm1").FullName
          Import-Module $modulePath -DisableNameChecking
          SetTokenAndRepository -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -repository "$ENV:GITHUB_REPOSITORY" -github
          $releases = @(gh release list --repo $ENV:GITHUB_REPOSITORY | ForEach-Object { $_.split("`t")[0] })
          Write-Host "Releases: $($releases -join ', ')"
          if ($releases.Count -eq 1) {
            $releasesJSon = "[$($releases | ConvertTo-Json -compress)]"
          }
          else {
            $releasesJSon = $releases | ConvertTo-Json -compress
          }
          Add-Content -Path $env:GITHUB_OUTPUT -Value "releases=$releasesJson"
          Write-Host "releases=$releasesJson"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "releasesCount=$($releases.Count)"
          Write-Host "releasesCount=$($releases.Count)"

  TestAlGo:
    runs-on: [ windows-latest ]
    needs: [ SetupRepositories ]
    strategy:
      matrix:
        private: [ 'Y', 'N' ]
        appSource: [ 'Y', 'N' ]
        multiProject: [ 'Y', 'N' ]
        linux: [ 'Y', 'N' ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Calculate parameters
        if: calculateParams
        run: |
          if ('${{ matrix.appSource }}' == 'N' -and '${{ matrix.multiProject }}' -eq 'N' -and '${{ matrix.linux }}' -eq 'N') {
            Add-Content -Path $env:GITHUB_OUTPUT -Value "adminCenterApiCredentialsParam='-adminCenterApiCredentials ${{ secrets.adminCenterApiCredentials }}'"
          }
          if ('${{ matrix.appSource }}' == 'Y') {
            Add-Content -Path $env:GITHUB_OUTPUT -Value "licenseFileUrlParam='-licenseFileUrl ${{ secrets.licenseFileUrl }}"
            Add-Content -Path $env:GITHUB_OUTPUT -Value "templateParam=-template '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}'
          }
          else {
            Add-Content -Path $env:GITHUB_OUTPUT -Value "templateParam=-template '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}'
          }

      - name: Run tests
        if: matrix.appSource == 'N' && matrix.multiProject == 'N' && matrix.linux == 'N'
        run: e2eTests\Test-AL-Go.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -InsiderSasToken '${{ Secrets.InsiderSasToken }}' ${{ steps.calculateParams.outputs.templateParam }} ${{ steps.calculateParams.outputs.adminCenterApiCredentialsParam }} ${{ steps.calculateParams.outputs.licenseFileUrlParam }} -appSource:('${{ matrix.appSource }}' -eq 'Y')

  TestAlGoUpgrade:
    runs-on: [ windows-latest ]
    needs: [SetupRepositories, CalculateReleases ]
    strategy:
      matrix:
        release: ${{ fromJson(needs.CalculateReleases.outputs.releases) }}
        appSource: [ 'Y', 'N' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Calculate parameters
        if: calculateParams
        run: |
          if ('${{ matrix.appSource }}' == 'Y') {
            Add-Content -Path $env:GITHUB_OUTPUT -Value "licenseFileUrlParam='-licenseFileUrl ${{ secrets.licenseFileUrl }}"
            Add-Content -Path $env:GITHUB_OUTPUT -Value "templateParam=-template '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}'
            Add-Content -Path $env:GITHUB_OUTPUT -Value "path='AppSource App'"
          }
          else {
            Add-Content -Path $env:GITHUB_OUTPUT -Value "templateParam=-template '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}'
            Add-Content -Path $env:GITHUB_OUTPUT -Value "path='pte'"
          }

      - name: Run tests
        run: e2eTests\Test-AL-Go-Upgrade.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' ${{ steps.calculateParams.outputs.templateParam }} ${{ steps.calculateParams.outputs.licenseFileUrlParam }} -appSource:('${{ matrix.appSource }}' -eq 'Y') -release '${{ matrix.release }}' -path 'pte'
         {{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}' -release '${{ matrix.release }}' -licenseFileUrl '${{ Secrets.LicenseFileUrl }}' -path 'appsourceapp' -appSourceApp

  RemoveRepositories:
    runs-on: [ windows-latest ]
    needs: [ SetupRepositories, TestAlGo, TestAlGoUpgrade ]
    if: always() && (${{ needs.SetupRepositories.result == 'Success' }})
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Remove Repositories
        run: e2eTests\RemoveRepositories.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -actionsRepo '${{ needs.SetupRepositories.outputs.actionsRepo }}' -perTenantExtensionRepo '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -appSourceAppRepo '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}'
