name: End to end tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  SetupRepositories:
    runs-on: [ windows-latest ]
    outputs:
      actionsRepo: ${{ steps.setup.outputs.actionsRepo }}
      perTenantExtensionRepo: ${{ steps.setup.outputs.perTenantExtensionRepo }}
      appSourceAppRepo: ${{ steps.setup.outputs.appSourceAppRepo }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Repositories
        id: setup
        run: e2eTests\SetupRepositories.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}'

  TestAlGoPte:
    runs-on: [ windows-latest ]
    needs: [ SetupRepositories ]
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: e2eTests\Test-AL-Go.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -adminCenterApiCredentials '${{ Secrets.adminCenterApiCredentials }}'

  TestAlGoPteMultiProject:
    runs-on: [ windows-latest ]
    needs: [ SetupRepositories ]
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: e2eTests\Test-AL-Go.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -multiProject

  TestAlGoAppSource:
    runs-on: [ windows-latest ]
    needs: [SetupRepositories ]
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: e2eTests\Test-AL-Go.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}' -adminCenterApiCredentials '' -licenseFileUrl '${{ Secrets.LicenseFileUrl }}' -appSourceApp

  TestAlGoAppSourceMultiProject:
    runs-on: [ windows-latest ]
    needs: [ SetupRepositories ]
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: e2eTests\Test-AL-Go.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}' -adminCenterApiCredentials '' -licenseFileUrl '${{ Secrets.LicenseFileUrl }}' -multiProject -appSourceApp

  TestAlGoUpdatePteV0:
    runs-on: [ windows-latest ]
    needs: [SetupRepositories ]
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: e2eTests\Test-AL-Go-Update.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -path 'testpte-v0'

  TestAlGoUpdateAppSourceV0:
    runs-on: [ windows-latest ]
    needs: [SetupRepositories ]
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: e2eTests\Test-AL-Go-Update.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -template '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}' -licenseFileUrl '${{ Secrets.LicenseFileUrl }}' -appSourceApp -path 'testappsource-v0'

  RemoveRepositories:
    runs-on: [ windows-latest ]
    needs: [ SetupRepositories, TestAlGoPte, TestAlGoPteMultiProject, TestAlGoAppSource, TestAlGoAppSourceMultiProject, TestAlGoUpdatePteV0, TestAlGoUpdateAppSourceV0 ]
    if: always() && (${{ needs.SetupRepositories.result == 'Success' }})
    steps:
      - uses: actions/checkout@v2

      - name: Remove Repositories
        run: e2eTests\RemoveRepositories.ps1 -github -githubOwner '${{ Secrets.githubOwner }}' -token '${{ Secrets.OrgPAT }}' -actionsRepo '${{ needs.SetupRepositories.outputs.actionsRepo }}' -perTenantExtensionRepo '${{ needs.SetupRepositories.outputs.perTenantExtensionRepo }}' -appSourceAppRepo '${{ needs.SetupRepositories.outputs.appSourceAppRepo }}'
